services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ${PROJECT_ROOT:-../public_html}:/var/www
      - ./certs:/etc/nginx/certs
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - php80
      - php81
      - php82
    container_name: nginx

  php80:
    build:
      context: .
      dockerfile: images/php80/Dockerfile
    restart: always
    volumes:
      - ${PROJECT_ROOT:-../public_html}:/var/www
    container_name: php80

  php81:
    build:
      context: .
      dockerfile: images/php81/Dockerfile
    restart: always
    volumes:
      - ${PROJECT_ROOT:-../public_html}:/var/www
    container_name: php81

  php82:
    build:
      context: .
      dockerfile: images/php82/Dockerfile
    restart: always
    volumes:
      - ${PROJECT_ROOT:-../public_html}:/var/www
    container_name: php82
      
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laragon
      MYSQL_USER: laragon
      MYSQL_PASSWORD: laragon
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    container_name: phpmyadmin

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    container_name: mailhog

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis

volumes:
  mysql_data:

name: docker-laragon